# Generated by Django 5.2.5 on 2025-11-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_faculty_room_activity_section_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
    ]
