# Generated by Django 5.2.5 on 2025-11-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_schedule_duration'),
        ('hello', '0007_auto_20251102_0454'),
    ]

    operations = [
    ]
