# Generated by Django 5.2.5 on 2025-11-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_merge_20251102_0455'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='employment_status',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contractual', 'Contractual')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='prc_licensed',
            field=models.BooleanField(default=False, verbose_name='PRC Licensed (Qualified)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='specialized_faculty', to='hello.course'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
