# Generated by Django 5.2.5 on 2025-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_faculty_employment_status_faculty_gender_and_more'),
    ]

    operations = [
        # Add the new fields first so subsequent operations that reference them succeed
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.CharField(choices=[('casal', 'Casal'), ('arlegui', 'Arlegui')], default='casal', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['campus', 'room_number']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='entity_type',
            field=models.CharField(choices=[('course', 'Course'), ('curriculum', 'Curriculum'), ('faculty', 'Faculty'), ('section', 'Section'), ('room', 'Room'), ('schedule', 'Schedule')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory')], default='lecture', max_length=20),
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
    ]
