# Generated by Django 5.2.5 on 2025-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_room_options_alter_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, default='000', max_length=20),
        ),
    ]
