# Generated by Django 5.2.5 on 2025-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_alter_room_unique_together_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete Schedule'), ('incomplete', 'No Schedule Yet')], default='incomplete', max_length=20),
        ),
    ]
